server:
  port: 8082
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/yourhockey
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
logging:
  file:
    name: app.log

product.photo.dir: images

---
spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
