server:
  port: 8082
spring:
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/yourhockey
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    separator: ;;
  jpa:
    show-sql: false
    #    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        jdbc.lob.non_contextual_creation: true
        format_sql: true
#logging:
#  file: app.log
#  level:
#    io.gunmarket.demo: TRACE
product.photo.dir: images
logging:
  level:
    root: off
