SELECT 1;

INSERT INTO public.brand (full_name, short_name) VALUES ('Adar', 'Adar');
INSERT INTO public.brand (full_name, short_name) VALUES ('Antonio Zoli', 'Antonio Zoli');
INSERT INTO public.brand (full_name, short_name) VALUES ('Armsan', 'Armsan');
INSERT INTO public.brand (full_name, short_name) VALUES ('Ata Arms', 'Ata Arms');
INSERT INTO public.brand (full_name, short_name) VALUES ('Ataman', 'Ataman');
INSERT INTO public.brand (full_name, short_name) VALUES ('Baikal', 'Baikal');
INSERT INTO public.brand (full_name, short_name) VALUES ('Benelli', 'Benelli');
INSERT INTO public.brand (full_name, short_name) VALUES ('Beretta', 'Beretta');
INSERT INTO public.brand (full_name, short_name) VALUES ('Bettinsoli', 'Bettinsoli');
INSERT INTO public.brand (full_name, short_name) VALUES ('Blaser', 'Blaser');
INSERT INTO public.brand (full_name, short_name) VALUES ('Breda', 'Breda');
INSERT INTO public.brand (full_name, short_name) VALUES ('Bronco', 'Bronco');
INSERT INTO public.brand (full_name, short_name) VALUES ('Browning', 'Browning');
INSERT INTO public.brand (full_name, short_name) VALUES ('CZ', 'CZ');
INSERT INTO public.brand (full_name, short_name) VALUES ('Fabarm', 'Fabarm');
INSERT INTO public.brand (full_name, short_name) VALUES ('Franchi', 'Franchi');
INSERT INTO public.brand (full_name, short_name) VALUES ('Hatsan', 'Hatsan');
INSERT INTO public.brand (full_name, short_name) VALUES ('Huglu', 'Huglu');
INSERT INTO public.brand (full_name, short_name) VALUES ('Impala', 'Impala');
INSERT INTO public.brand (full_name, short_name) VALUES ('Krieghoff', 'Krieghoff');
INSERT INTO public.brand (full_name, short_name) VALUES ('Mannlicher', 'Mannlicher');
INSERT INTO public.brand (full_name, short_name) VALUES ('Marocchi', 'Marocchi');
INSERT INTO public.brand (full_name, short_name) VALUES ('Merkel', 'Merkel');
INSERT INTO public.brand (full_name, short_name) VALUES ('Monza', 'Monza');
INSERT INTO public.brand (full_name, short_name) VALUES ('Orsis', 'Orsis');
INSERT INTO public.brand (full_name, short_name) VALUES ('Pietta', 'Pietta');
INSERT INTO public.brand (full_name, short_name) VALUES ('ProArms Armory', 'ProArms Armory');
INSERT INTO public.brand (full_name, short_name) VALUES ('Sabatti', 'Sabatti');
INSERT INTO public.brand (full_name, short_name) VALUES ('Sako', 'Sako');
INSERT INTO public.brand (full_name, short_name) VALUES ('Sauer', 'Sauer');
INSERT INTO public.brand (full_name, short_name) VALUES ('Seylan', 'Seylan');
INSERT INTO public.brand (full_name, short_name) VALUES ('Steyr Arms', 'Steyr Arms');
INSERT INTO public.brand (full_name, short_name) VALUES ('Stoeger', 'Stoeger');
INSERT INTO public.brand (full_name, short_name) VALUES ('Strasser', 'Strasser');
INSERT INTO public.brand (full_name, short_name) VALUES ('Tikka', 'Tikka');
INSERT INTO public.brand (full_name, short_name) VALUES ('Winchester', 'Winchester');
INSERT INTO public.brand (full_name, short_name) VALUES ('ЗИД', 'ЗИД');
INSERT INTO public.brand (full_name, short_name) VALUES ('ЗМЗ', 'ЗМЗ');
INSERT INTO public.brand (full_name, short_name) VALUES ('Концерн Калашников', 'Концерн Калашников');
INSERT INTO public.brand (full_name, short_name) VALUES ('Молот', 'Молот');
INSERT INTO public.brand (full_name, short_name) VALUES ('Молот Армз', 'Молот Армз');
INSERT INTO public.brand (full_name, short_name) VALUES ('Техкрим', 'Техкрим');
INSERT INTO public.brand (full_name, short_name) VALUES ('ТОЗ', 'ТОЗ');
INSERT INTO public.brand (full_name, short_name) VALUES ('Тула', 'Тула');
INSERT INTO public.brand (full_name, short_name) VALUES ('Форт', 'Форт');

INSERT INTO public.caliber (name) VALUES ('10x22');
INSERT INTO public.caliber (name) VALUES ('11,43x23');
INSERT INTO public.caliber (name) VALUES ('12x70');
INSERT INTO public.caliber (name) VALUES ('12x76');
INSERT INTO public.caliber (name) VALUES ('12x89');
INSERT INTO public.caliber (name) VALUES ('17 HMR');
INSERT INTO public.caliber (name) VALUES ('20x76');
INSERT INTO public.caliber (name) VALUES ('22 LR');
INSERT INTO public.caliber (name) VALUES ('22 WMR');
INSERT INTO public.caliber (name) VALUES ('223 Rem');
INSERT INTO public.caliber (name) VALUES ('243 Win');
INSERT INTO public.caliber (name) VALUES ('28x70');
INSERT INTO public.caliber (name) VALUES ('30-06');
INSERT INTO public.caliber (name) VALUES ('300 WinMag');
INSERT INTO public.caliber (name) VALUES ('308 Win');
INSERT INTO public.caliber (name) VALUES ('338 LM');
INSERT INTO public.caliber (name) VALUES ('345ТК');
INSERT INTO public.caliber (name) VALUES ('366 ТКМ');
INSERT INTO public.caliber (name) VALUES ('40 S&W');
INSERT INTO public.caliber (name) VALUES ('410');
INSERT INTO public.caliber (name) VALUES ('411 TKM');
INSERT INTO public.caliber (name) VALUES ('45 Auto');
INSERT INTO public.caliber (name) VALUES ('45-70');
INSERT INTO public.caliber (name) VALUES ('5,45x39');
INSERT INTO public.caliber (name) VALUES ('6,5 Creedmoor');
INSERT INTO public.caliber (name) VALUES ('6,5x38');
INSERT INTO public.caliber (name) VALUES ('6,5x39');
INSERT INTO public.caliber (name) VALUES ('6,5x55');
INSERT INTO public.caliber (name) VALUES ('7,62x38');
INSERT INTO public.caliber (name) VALUES ('7,62x39');
INSERT INTO public.caliber (name) VALUES ('7,62x54');
INSERT INTO public.caliber (name) VALUES ('8x68');
INSERT INTO public.caliber (name) VALUES ('9,3x62');
INSERT INTO public.caliber (name) VALUES ('9,6x53 Lancaster');
INSERT INTO public.caliber (name) VALUES ('9x18');
INSERT INTO public.caliber (name) VALUES ('9x19');
INSERT INTO public.caliber (name) VALUES ('9x22');
INSERT INTO public.caliber (name) VALUES ('9x39');

INSERT INTO public.principle_of_operation (name) VALUES ('газоотводные');
INSERT INTO public.principle_of_operation (name) VALUES ('инерционные');
INSERT INTO public.principle_of_operation (name) VALUES ('кривошипно-шатунные');
INSERT INTO public.principle_of_operation (name) VALUES ('переломные');
INSERT INTO public.principle_of_operation (name) VALUES ('помповые');
INSERT INTO public.principle_of_operation (name) VALUES ('продольно-скользящие');
INSERT INTO public.principle_of_operation (name) VALUES ('штуцера');
