name: MASTER

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
          java-package: jdk
          architecture: x64
      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: 11
          postgresql db: yourhockey
          postgresql user: postgres
          postgresql password: root
      - name: Build with Maven
        run: mvn -B package
      - name: Temp step with almost dead Gilberto
        run: |
          NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
          echo "New version: ${NEW_VERSION}"
          echo "Github username: ${GITHUB_ACTOR}"
          PAYLOAD=$(find target -maxdepth 1 -name *.jar)
          echo "Send ${PAYLOAD} to Gilberto"
      - name: Copy Jar via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          source: "$(find target -maxdepth 1 -name *.jar)"
          target: "/opt/prod"
      - name: Start App
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            sudo service yourhockey restart
